config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }


  root to: 'services#home'
  root to: "home#index"

  resources :services, only: [ :home, :show, :index ]  do
    resources :proposals, only: [ :show, :create, :index, :new ]
  end



  resources :my_services


  resources :my_services do
    collection do
      get :recuse
      post :recuse
    end
  end



  resources :my_proposals, only: [ :show, :index, :edit, :update, :destroy ] do
    member do
        patch :finish
    end
  end

  resources :received_proposals, only: [ :show, :index ] do
    member do
      patch :accept
      patch :decline
      patch :finish
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Attachinary::Engine => "/attachinary"
end

app/models/service.rb
class Service < ApplicationRecord
  CATEGORIES = ["Arquitetura", "Web Design", "Programador Ruby Rails"]
  belongs_to :user
  has_many :proposals, dependent: :destroy
  validates :description, presence: true
  validates :user, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }
  has_attachments :photos, maximum: 20
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index]

  def home
    @categories = Service::CATEGORIES
  end

  def index
    @services = Service.where(category: params[:category])

    @services_with_address = @services.joins(:user).where.not("users.latitude is null and users.longitude is null")

    # @users = @services.map(&:user)

    @hash = Gmaps4rails.build_markers(@services_with_address) do |service, marker|
      marker.lat service.user.latitude
      marker.lng service.user.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
    end
  end


  # def new
  #   @service = Service.new
  # end

  # def create
  #   @service = Service.new(service_params)
  #   if @service.save
  #     flash[:notice] = "#{@service.description} adicionado"
  #     redirect_to new_service_path
  #   else
  #     render :new
  #   end
  # end

  # def destroy
  #   @service = Service.find(params[:id])
  #   @service.destroy
  #   redirect_to services_path(category: @service.category)
  # end

  def show
    @service = Service.find(params[:id])
    @proposal = @service.proposals.new(user: current_user)
    @proposal_list = Proposal.where( service_id: @service )
  end

  # private

  # def service_params
  #   # *Strong params*: You need to *whitelist* what can be updated by the use
  #   # Never trust user data!
  #   params.require(:service).permit(:description, :category)
  # end
end

app/views/services/_card.html.erb
<div class="container-fluid">
    <div class="col-xs-12 col-sm-4">
      <div class="card-serv" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path background_url(@service), height: 300, width: 400, crop: :fill %>')">
      <div class="card-user-service">
        <%= @service.user.first_name %>
      </div>
      <div class="card-category-service">
        <%= @service.category %>
      </div>

       <div class="card-description-service">
        <h2><%= @service.description %></h2>
        </div>

      </div>
    </div>
  <%= render 'proposal' %>

</div>

app/views/services/_form.html.erb
<div class="col-xs-12 col-sm-4">
  <h3> Criar Serviço</h3>
  <br>
    <%= simple_form_for [@service] do |f| %>
      <%= f.input :description, label: 'Descrição Serviço' %>
      <%= f.input :category, label: 'Categoria' %>
      <%= f.input :user_id, label: 'User ID' %>
      <%= f.input :photos, as: :attachinary %>
      <%= f.submit "Add", class: "btn btn-primary" %>
      <%= link_to "Back", services_path, :method => "get", :class=>"btn btn-warning" %>
    <% end %>
</div>

app/views/services/_proposal.html.erb
<div class="proposal-area col-xs-12 col-sm-4">
   <!--  <h5> Criar Proposta</h5> -->
    <%= simple_form_for [@service, @proposal] do |f| %>
      <%= f.input :description, label: 'Criar Proposta', input_html: { style: 'width: 800px;
    height: 170px;'}  %>
      <%= f.input :user_id, :as => :hidden, label: 'User ID' %>
      <%= f.input :service_id, :as => :hidden,label: 'Service ID' %>
      <% f.input :photos, as: :attachinary %>
      <%= f.submit "Adicionar", class: "btn btn-primary" %>
      <%= link_to "Voltar", services_path(category: @service.category), :method => "get", :class=>"btn btn-warning" %>
    <% end %>
</div>

app/views/services/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('http://az616578.vo.msecnd.net/files/2016/07/28/636053241284023565-1698910486_635993185839763884-1853824258_high%20school%20graduation.jpg');">
  <div class="banner-content">
    <h1>Tchau Facul</h1>
    <p>O mercado de trabalho te espera</p>
   <!--  <a <%= link_to "CLIQUE AQUI", services_path, :method => "get", :class=>"btn btn-primary btn-lg"  %></a> -->
  </div>
</div>


<div class="col-md-12 text-center padded margin-fix-bottom"><h2>Our juniors have skills</h2></div>
<br>
<br>
<br>
<section class="carousel slide padded" data-ride="carousel" id="postsCarousel">

    <div class="row">
      <div class="carousel slide text-center" data-ride="carousel" data-type="multi" data-interval="3000" id="myCarousel">
      <div class="container p-t-0 m-t-2 carousel-inner">
          <div class="row row-equal carousel-item active m-t-0">
          <% @categories.each do |category| %>
              <div class="col-md-4">
                  <div class="card">
                      <div class="card-img-top card-img-top-250">
                          <img class="img-fluid" src="http://i.imgur.com/EW5FgJM.png" alt="Carousel 1">
                      </div>
                      <div class="card-block p-t-2">
                          <h4>
                              <a href><%= link_to category, services_path(category: category) %></a>
                          </h4>
                      </div>
                  </div>
              </div>
            <% end %> -->
         </div>
         </div>
         <a class="left carousel-control" href="#myCarousel" data-slide="prev"><i class="glyphicon glyphicon-chevron-left"></i></a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next"><i class="glyphicon glyphicon-chevron-right"></i></a>
      </div>
    </div>
</section>

app/views/services/index.html.erb
<div class="container padded">
  <h2> Find skilled juniors on <strong><%= params[:category] %></strong>  </h2>
</div>
<hr>

<div class="container padded">
  <div class="row">
    <% @services.each do |service| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card-serv" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path background_url(service), height: 300, width: 400, crop: :fill %>')">
      <div class="card-category"><%= service.category %></div>
       <div class="card-description">
          <h2><%= service.description %></h2>
        </div>
        <%= link_to "", service_path(service), class: "card-link" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div id="map" style="width: 100%; height: 500px; margin-bottom: 50px;">
    <% content_for(:after_js) do %>
      <%= javascript_tag do %>
        $(document).ready(function() {
          var handler = Gmaps.build('Google');
          handler.buildMap({ internal: { id: 'map' } }, function() {
            markers = handler.addMarkers(<%= raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
            if (markers.length == 0) {
              handler.getMap().setZoom(2);
            } else if (markers.length == 1) {
              handler.getMap().setZoom(16);
            }
          });
        });
      <% end %>
    <% end %>
  </div>
</div>

app/views/services/new.html.erb
<%= render 'form' %>
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>

app/views/services/show.html.erb
<div class="container table-status">
  <div>
      <%= render "card" %>
  </div>
  <br>
<h3> List of proposals </h3>
  <br>

  <div class="tab">
   <!--  <button class="tablinks" onclick="openCity(event, 'New')">New</button>
   <button class="tablinks" onclick="openCity(event, 'Accepted')">Accepted</button>
   <button class="tablinks" onclick="openCity(event, 'Declined')">Declined</button> -->
    <button class="tablinks" onclick="openCity(event, 'All')">Proposals</button>
  </div>

  <!-- <div id="New" class="tabcontent">
    <table class="table table-sm">
      <thead>
        <tr>
          <th>Description</th>
          <th>Status</th>
          <th>Accepted</th>
          <th>Declined</th>
        </tr>
      </thead>
      <tbody>
      <% @proposal_list.each do |proposal| %>
        <% if proposal.status == 'New'  %>
        <tr>
          <td><%= link_to "#{proposal.description}", my_proposal_path(proposal) %></td>
          <td><%= proposal.status %></td>
          <td><%= link_to "Aceitar", accept_received_proposal_path(proposal), method: :patch, class:"btn btn-primary" %></td>
          <td><%= link_to "Recusar", decline_received_proposal_path(proposal), method: :patch, class:"btn btn-danger" %></td>
        </tr>
        <% else %>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>

  <div id="Accepted" class="tabcontent">
    <table class="table table-sm">
      <thead>
        <tr>
          <th>Description</th>
          <th>Status</th>
          <th>Accepted</th>
          <th>Declined</th>
        </tr>
      </thead>
      <tbody>
      <% @proposal_list.each do |proposal| %>
        <% if proposal.status == 'Accepted'  %>
        <tr>
          <td><%= link_to "#{proposal.description}", my_proposal_path(proposal) %></td>
          <td><%= proposal.status %></td>
          <% if proposal.status == 'Accepted'  %>
                  <td> </td>
                <% else %>
                  <td><%= link_to "Aceitar", accept_received_proposal_path(proposal), method: :patch, class:"btn btn-primary" %></td>
              <% end %>

             <% if proposal.status == 'Declined'  %>
                  <td> </td>
                <% else %>
              <td><%= link_to "Recusar", decline_received_proposal_path(proposal), method: :patch, class:"btn btn-danger" %></td>
              <% end %>
        </tr>
        <% else %>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>

  <div id="Declined" class="tabcontent">
    <table class="table table-sm">
      <thead>
        <tr>
          <th>Description</th>
          <th>Status</th>
          <th>Accepted</th>
          <th>Declined</th>
        </tr>
      </thead>
      <tbody>
      <% @proposal_list.each do |proposal| %>
        <% if proposal.status == 'Declined'  %>
        <tr>
          <td><%= link_to "#{proposal.description}", my_proposal_path(proposal) %></td>
          <td><%= proposal.status %></td>
          <% if proposal.status == 'Accepted'  %>
                  <td> </td>
                <% else %>
                  <td><%= link_to "Aceitar", accept_received_proposal_path(proposal), method: :patch, class:"btn btn-primary" %></td>
              <% end %>

             <% if proposal.status == 'Declined'  %>
                  <td> </td>
                <% else %>
              <td><%= link_to "Recusar", decline_received_proposal_path(proposal), method: :patch, class:"btn btn-danger" %></td>
              <% end %>
        </tr>
        <% else %>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div> -->

  <div id="All" class="tabcontent">
    <table class="table table-sm">
          <thead>
            <tr>
              <th>Descrição</th>
              <th>Status</th>
              </tr>
          </thead>
          <tbody>
          <% @proposal_list.each do |proposal| %>
            <td><%= link_to "#{proposal.description}", my_proposal_path(proposal) %></td>
              <td><%= proposal.status %></td>
              <% if proposal.status = 'Accepted'  %>
                  <td> </td>
                <% else %>
                  <!-- <td><%= link_to "Aceitar", accept_received_proposal_path(proposal), method: :patch, class:"btn btn-primary" %></td> -->
              <% end %>

             <% if proposal.status == 'Declined'  %>
                  <td> </td>
                <% else %>
             <!--  <td><%= link_to "Recusar", decline_received_proposal_path(proposal), method: :patch, class:"btn btn-danger" %></td> -->
              <% end %>
            </tr>
          <% end %>
          </tbody>
        </table>
  </div>
</div>

<% content_for :after_js do %>
  <%= javascript_tag do %>
    openCity(event, 'All')
  <% end %>
<% end %>