config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }


  root to: 'services#home'
  root to: "home#index"

  resources :services, only: [ :home, :show, :index ]  do
    resources :proposals, only: [ :show, :create, :index, :new ]
  end



  resources :my_services


  resources :my_services do
    collection do
      get :recuse
      post :recuse
    end
  end



  resources :my_proposals, only: [ :show, :index, :edit, :update, :destroy ] do
    member do
        patch :finish
    end
  end

  resources :received_proposals, only: [ :show, :index ] do
    member do
      patch :accept
      patch :decline
      patch :finish
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Attachinary::Engine => "/attachinary"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "https://t4.ftcdn.net/jpg/01/32/63/49/240_F_132634920_Opt6PM9Sbpz1pjAVppCjX0tWiesD7q3L.jpg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <!-- <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <!-- <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %> -->

      <!-- Button (call-to-action) -->
      <%= link_to t(".top_call_to_action", default: "My Services"), my_services_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
      <%= link_to t(".top_call_to_action", default: "My interests"), my_proposals_path, class: "navbar-wagon-item navbar-wagon-button btn" %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">

        <div class="dropdown">
          <%= image_tag avatar_url(current_user), class: "avatar dropdown-toggle", id: "navbar-avatar", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Edit Profile") %>
              <% end %>
            </li>

            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>

            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>

          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-button btn" %>

    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Home", root_path%></li>
        <li> <%= link_to "Edit Profile", edit_user_registration_path%></li>
        <li><%= link_to "Logout", destroy_user_session_path%></li>
      </ul>
    </div>
  </div>
</div>