config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }


  root to: 'services#home'
  root to: "home#index"

  resources :services, only: [ :home, :show, :index ]  do
    resources :proposals, only: [ :show, :create, :index, :new ]
  end



  resources :my_services


  resources :my_services do
    collection do
      get :recuse
      post :recuse
    end
  end



  resources :my_proposals, only: [ :show, :index, :edit, :update, :destroy ] do
    member do
        patch :finish
    end
  end

  resources :received_proposals, only: [ :show, :index ] do
    member do
      patch :accept
      patch :decline
      patch :finish
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Attachinary::Engine => "/attachinary"
end

app/controllers/my_proposals_controller.rb
class MyProposalsController < ApplicationController
  before_action :set_my_proposal, only: [:edit, :update, :destroy]

  def index
    @my_proposals = current_user.proposals
  end

  def show
    @my_proposal = Proposal.find(params[:id])
    #@service = Service.find(params[:id])
  end

  def edit
    @service = @my_proposal.service
  end

  def update
    @my_proposal = Proposal.find(params[:id])
    if @my_proposal.update_attributes(my_proposal_params)
      redirect_to my_proposal_path(@my_proposal)
    else
      render :edit
    end
  end

  def destroy
    @my_proposal.destroy
    redirect_to my_proposals_path
  end

  def finish
  end

  private

  def set_my_proposal
    @my_proposal = current_user.proposals.find(params[:id])
  end

  def my_proposal_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:proposal).permit(:description, photos: [])
  end
end

app/views/my_proposals/edit.html.erb
<div class="container">
  <h1>Edit your proposal</h1>
  <div class="col-xs-12 col-sm-4">
      <%= simple_form_for @my_proposal, url: my_proposal_path(@my_proposal) do |f| %>
        <%= f.input :description, label: 'Proposta', input_html: { style: 'width: 1150px; height: 220px '} %>
        <%= f.input :user_id, as: :hidden, label: 'User ID' %>
        <%= f.input :service_id, as: :hidden,label: 'Service ID' %>

        <%= f.submit "Update", class: "button-update btn btn-primary" %>
        <%= link_to "Delete", my_proposal_path(@my_proposal), method: "delete", class: "button-update btn btn-danger" %>
        <%= link_to "Back", my_proposal_path(@my_proposal), method: "get", class: "button-update btn btn-warning" %>
      <% end %>
  </div>
</div>

app/views/my_proposals/index.html.erb
<div class="container padded">
  <h2 class="text-left margin-fix-bottom">List with proposal sent </h2>
    <div class="row">

      <% @my_proposals.each do |my_proposal| %>
        <div class="col-xs-12 col-sm-4">
          <div class="card-proposal gradient">

              <div class="card-avatar-service-user">
                <h2><%= image_tag avatar_url(my_proposal.service.user), id: "proposal-avatar"%></h2>
              </div>

              <div class="card-service-user">
                <h2 id="text-user"> Proposal to <%= link_to my_proposal.service.user.first_name,service_path(my_proposal.service), id: "link-user" %></h2>
              </div>

              <div class="card-category">
                <h3 id="text-category"> <%= link_to my_proposal.service.category, services_path(category: my_proposal.service.category), id: "link-category" %> </h3>
              </div>

              <div class="card-description">
                <h4><%= my_proposal.service.description %></h4>
              </div>

              <%= link_to "See details", my_proposal_path(my_proposal), class: "card-button btn btn-primary"%>

          </div>
        </div>

      <% end %>
    </div>
</div>

app/views/my_proposals/show.html.erb
<div class = "container text-detail">
  <div class="col-md-12 padded margin-fix-bottom">
      <h1>My proposal to this service</h1>
      <br>
      <h4><%= @my_proposal.description %></h4>
      <%= link_to 'Edit my proposal', edit_my_proposal_path(@my_proposal), class: "button-show btn-md btn btn-primary" %>
      <%= link_to "Back", :back, class: "button-show btn-md btn btn-warning " %>
  </div>
</div>