config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }


  root to: 'services#home'
  root to: "home#index"

  resources :services, only: [ :home, :show, :index ]  do
    resources :proposals, only: [ :show, :create, :index, :new ]
  end



  resources :my_services


  resources :my_services do
    collection do
      get :recuse
      post :recuse
    end
  end



  resources :my_proposals, only: [ :show, :index, :edit, :update, :destroy ] do
    member do
        patch :finish
    end
  end

  resources :received_proposals, only: [ :show, :index ] do
    member do
      patch :accept
      patch :decline
      patch :finish
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Attachinary::Engine => "/attachinary"
end

app/controllers/my_services_controller.rb
class MyServicesController < ApplicationController
  before_action :set_my_service, only: [:show, :edit, :update, :destroy]

  def index
    @my_services = current_user.services
  end

  def new
    @my_service = Service.new
  end

  def create
    @my_service = current_user.services.new(my_service_params)
    if @my_service.save
      flash[:notice] = "#{@my_service.description} adicionado"
      redirect_to my_service_path(@my_service)
    else
      render :new
    end
  end

  def update
    if @my_service.update(my_service_params)
      redirect_to my_service_path(@my_service)
    else
      render :edit
    end
  end

  def show
  end

  def edit
  end

  def recuse
    @proposal = Proposal.find(params[:id])
    @proposal.status = "Declined"
  end


  def destroy
    @my_service.destroy
    redirect_to my_services_path
  end

  private

  def set_my_service
    @my_service = Service.find(params[:id])
  end

  def my_service_params
      # *Strong params*: You need to *whitelist* what can be updated by the user
      # Never trust user data!
      params.require(:service).permit(:description, :category, photos: [])
  end

end

app/views/my_services/edit.html.erb
<div class="container padded">
  <h2> Edit the skill <strong>"<%= @my_service.description.capitalize %>"</strong>, junior! </h2>
  <br>

  <%= simple_form_for @my_service, url: my_service_path do |f| %>
    <%= f.error_notification %>
    <%= f.input :category, prompt: "Which area would you like to find projects?", collection: Service::CATEGORIES %>
    <br>
    <%= f.input :description %>
    <br>
    <%= f.input :photos, as: :attachinary %>
    <br>
    <%= f.submit "Edit skill", class: "btn btn-primary" %>
  <% end %>

</div>

<hr>

app/views/my_services/index.html.erb
<div class="container padded">
  <h2>Your portfolio <strong>starts</strong> here, junior!</h2>
  <p>Create and organize your expertises. We will match projects for you.</p>

  <br>

  <%= link_to 'Add a new skill', new_my_service_path, class:"btn btn-primary" %>
</div>

<hr>
<div class="container padded">
  <h2 class="text-left margin-fix-bottom">List of Skills</h2>
   <div class="row">
     <% @my_services.each do |my_service| %>
     <div class="col-xs-12 col-sm-4">
       <div class="card-serv" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path background_url(my_service), height: 300, width: 400, crop: :fill %>')">
       <div class="card-category"><%= my_service.category %></div>
        <div class="card-description">
           <h2><%= my_service.description %></h2>
         </div>
         <%= link_to "", my_service_path(my_service), class: "card-link" %>
       </div>
     </div>
     <% end %>
   </div>
 </div>

app/views/my_services/new.html.erb
<div class="container padded">
<h2> Add a skill to your profile, junior! </h2>
<br>

<%= simple_form_for @my_service, url: my_services_path do |f| %>
  <%= f.error_notification %>
  <%= f.input :category, prompt: "Which area would you like to find projects?", collection: Service::CATEGORIES %>
  <br>
  <%= f.input :description %>
  <br>
  <%= f.input :photos, as: :attachinary %>
  <br>
  <%= f.submit "Add skill", class: "btn btn-success" %>
<% end %>
</div>

app/views/my_services/show.html.erb
<div class="container">
  <div class="skill-detail">
    <h2>Skill: <strong><%= @my_service.description.capitalize %></strong> </h2>
    <h4>Category: <strong><%= @my_service.category %></strong> </h4>
    <br>
      <%= link_to "Edit", edit_my_service_path(@my_service), class:"btn btn-warning" %>
      <%= link_to "Delete", my_service_path(@my_service), class:"btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %>
      <%= link_to "See all", my_services_path, class:"btn btn-primary" %>
    <br>
  </div>
  <br>

  <div class="tab">
    <button class="tablinks" onclick="openCity(event, 'New')">New</button>
    <button class="tablinks" onclick="openCity(event, 'Accepted')">Accepted</button>
    <button class="tablinks" onclick="openCity(event, 'Declined')">Declined</button>
    <button class="tablinks" onclick="openCity(event, 'Finished')">Finished</button>
    <button class="tablinks" onclick="openCity(event, 'All')">All</button>
  </div>

  <div id="New" class="tabcontent">
    <table class="table table-sm">
      <thead>
        <tr>
          <th>Description</th>
          <th>Status</th>
          <th>Accepted</th>
          <th>Declined</th>
          <th>Finished</th>
        </tr>
      </thead>
      <tbody>
      <% @my_service.proposals.each do |proposal| %>
        <% if proposal.status == 'New'  %>
        <tr>
          <td><%= link_to "#{proposal.description}", received_proposal_path(proposal) %></td>
          <td><%= proposal.status %></td>
          <td><%= link_to "Aceitar", accept_received_proposal_path(proposal), method: :patch, class:"btn btn-primary" %></td>
          <td><%= link_to "Recusar", decline_received_proposal_path(proposal), method: :patch, class:"btn btn-danger" %></td>
          <td><%= link_to "Finalizar", finish_received_proposal_path(proposal), method: :patch, class:"btn btn-success" %></td>
        </tr>
        <% else %>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>

  <div id="Accepted" class="tabcontent">
    <table class="table table-sm">
      <thead>
        <tr>
          <th>Description</th>
          <th>Status</th>
          <th>Accepted</th>
          <th>Declined</th>
          <th>Finished</th>
        </tr>
      </thead>
      <tbody>
      <% @my_service.proposals.each do |proposal| %>
        <% if proposal.status == 'Accepted'  %>
        <tr>
          <td><%= link_to "#{proposal.description}", received_proposal_path(proposal) %></td>
          <td><%= proposal.status %></td>
          <% if proposal.status == 'Accepted'  %>
                  <td> </td>
                <% else %>
                  <td><%= link_to "Aceitar", accept_received_proposal_path(proposal), method: :patch, class:"btn btn-primary" %></td>
              <% end %>

             <% if proposal.status == 'Declined'  %>
                  <td> </td>
                <% else %>
              <td><%= link_to "Recusar", decline_received_proposal_path(proposal), method: :patch, class:"btn btn-danger" %></td>
              <% end %>
              <td><%= link_to "Finalizar", finish_received_proposal_path(proposal), method: :patch, class:"btn btn-success" %></td>
        </tr>
        <% else %>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>

  <div id="Declined" class="tabcontent">
    <table class="table table-sm">
      <thead>
        <tr>
          <th>Description</th>
          <th>Status</th>
          <th>Accepted</th>
          <th>Declined</th>
          <th>Finished</th>
        </tr>
      </thead>
      <tbody>
      <% @my_service.proposals.each do |proposal| %>
        <% if proposal.status == 'Declined'  %>
        <tr>
          <td><%= link_to "#{proposal.description}", received_proposal_path(proposal) %></td>
          <td><%= proposal.status %></td>
          <% if proposal.status == 'Accepted'  %>
                  <td> </td>
                <% else %>
                  <td><%= link_to "Aceitar", accept_received_proposal_path(proposal), method: :patch, class:"btn btn-primary" %></td>
              <% end %>

             <% if proposal.status == 'Declined'  %>
                  <td> </td>
                <% else %>
              <td><%= link_to "Recusar", decline_received_proposal_path(proposal), method: :patch, class:"btn btn-danger" %></td>
              <% end %>
              <td><%= link_to "Finalizar", finish_received_proposal_path(proposal), method: :patch, class:"btn btn-success" %></td>
        </tr>
        <% else %>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>


  <div id="Finished" class="tabcontent">
    <table class="table table-sm">
      <thead>
        <tr>
          <th>Description</th>
          <th>Status</th>
          <th>Accepted</th>
          <th>Declined</th>
          <th>Finished</th>
        </tr>
      </thead>
      <tbody>
      <% @my_service.proposals.each do |proposal| %>
        <% if proposal.status == 'Finished'  %>
        <tr>
          <td><%= link_to "#{proposal.description}", received_proposal_path(proposal) %></td>
          <td><%= proposal.status %></td>
          <% if proposal.status == 'Finished'  %>
                  <td> </td>
                <% else %>
                  <td><%= link_to "Aceitar", accept_received_proposal_path(proposal), method: :patch, class:"btn btn-primary" %></td>
              <% end %>
             <% if proposal.status == 'Declined'  %>
                  <td> </td>
                <% else %>
              <td><%= link_to "Recusar", decline_received_proposal_path(proposal), method: :patch, class:"btn btn-danger" %></td>
              <% end %>
              <td><%= link_to "Finalizar", finish_received_proposal_path(proposal), method: :patch, class:"btn btn-success" %></td>

        </tr>
        <% else %>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>








  <div id="All" class="tabcontent">
    <table class="table table-sm">
          <thead>
            <tr>
              <th>Descrição</th>
              <th>Status</th>
              <th>Accepted</th>
              <th>Declined</th>
              <th>Finished</th>
            </tr>
          </thead>
          <tbody>
          <% @my_service.proposals.each do |proposal| %>
            <tr>
              <td><%= link_to "#{proposal.description}", received_proposal_path(proposal) %></td>
              <td><%= proposal.status %></td>
              <% if proposal.status == 'Accepted'  %>
                  <td> </td>
                <% else %>
                  <td><%= link_to "Aceitar", accept_received_proposal_path(proposal), method: :patch, class:"btn btn-primary" %></td>
              <% end %>

             <% if proposal.status == 'Declined'  %>
                  <td> </td>
                <% else %>
              <td><%= link_to "Recusar", decline_received_proposal_path(proposal), method: :patch, class:"btn btn-danger" %></td>
              <td><%= link_to "Finalizar", finish_received_proposal_path(proposal), method: :patch, class:"btn btn-success" %></td>
              <% end %>
            </tr>
          <% end %>
          </tbody>
        </table>
  </div>
</div>

<% content_for :after_js do %>
  <%= javascript_tag do %>
    openCity(event, 'All')
  <% end %>
<% end %>